spring.datasource.url=jdbc:postgresql://localhost:5432/project
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=Dxs@0038

# H2 console (view database in browser)
# spring.h2.console.enabled=true
# spring.h2.console.path=/h2-console

# Auto-create tables from your entity classes
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true