spring.datasource.url=${JDBC_DATABASE_URL:jdbc:postgresql://project_j5jh_user:fVTIwDzEgnT7fVNXmKp4xaYGJa8BL8kR@dpg-d9sqorvavr4c73bdvp0g-a/project_j5jh}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${JDBC_DATABASE_USERNAME:project_j5jh_user}
spring.datasource.password=${JDBC_DATABASE_PASSWORD:fVTIwDzEgnT7fVNXmKp4xaYGJa8BL8kR}

# H2 console (view database in browser)
# spring.h2.console.enabled=true
# spring.h2.console.path=/h2-console

# Auto-create tables from your entity classes
spring.jpa.hibernate.ddl-auto=update
server.port=${PORT:8080}

spring.jpa.show-sql=true